// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = "Netanel";    // Network SSID (name)
const char PASS[]     = "gc442244";    // Network password (use for WPA, or use as key for WEP)


float speed;
float lat =0;
float lon =0;
CloudLocation location;

void initProperties(){
  ArduinoCloud.addProperty(location, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(speed, READ, 1 * SECONDS, NULL);


}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
